version: "3.3"

services:
  app:
    build: .
    container_name: rcmltb
    command: bash start.sh
    #数据持久化，到那时个人觉得还可以添加一下用户数据本地化，在不使用数据库得前提下保存数据
    volumes:
      - //usr/src/app/users:/usr/src/app/downloads:rw
      - /usr/src/app/downloads:/usr/src/app/downloads:rw # optional
    ports:
      - "80:80" # qbittorrent selection webserver
      - "81:81" # local mirror files webserver
      - "8080:8080" # rclone serve index webserver
    restart: on-failure
      
      
