version: "3.3"

services:
  app:
    build: .
    container_name: rcmltb
    command: bash start.sh
    #数据持久化，在不使用数据库得前提下保存用户数据数据
    volumes:
      - /usr/src/app/users:/usr/src/app/users:rw
      - /usr/src/app/downloads:/usr/src/app/downloads:rw
    ports:
      - "80:80" # qbittorrent selection webserver
      - "81:81" # local mirror files webserver
      - "8080:8080" # rclone serve index webserver
    restart: on-failure
      
      
